---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "tv-data-lake.fullname" . }}
  labels:
    {{- include "tv-data-lake.labels" . | nindent 4 }}
  creationTimestamp: null
spec:
  tags:
    - annotations:
        openshift.io/imported-from: eformat/tv-data-lake
      from:
        kind: DockerImage
        name: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Values.image_version }}
      importPolicy: {}
      name: {{ .Chart.AppVersion }}
